[plugins]
"image.nvim" = "1.2.0"
"lua-utils.nvim" = "1.0.2"
"plenary.nvim" = "scm"
"rocks-config.nvim" = "1.2.3"
"rocks-dev.nvim" = "1.1.2"
"rocks-git.nvim" = "1.3.0"
"rocks.nvim" = "2.19.0"
"telescope.nvim" = "scm"
luarocks-build-rust-mlua = "0.2.0"
luasnip = "2.2.0"
nvim-dap = "0.7.0"
nvim-lspconfig = {version = "0.1.7"}
nvim-surround = "2.1.5"
nvim-web-devicons = "0.99"
rustaceanvim = "4.14.1"
neogit = "scm"
"kanagawa.nvim" = "scm"
"oil.nvim" = "scm"
neogen = "scm"
"twilight.nvim"= "scm"
"neodev.nvim"= "scm"
"zen-mode.nvim"= "scm"
"rocks-treesitter.nvim" = "scm"

# --------- TREESITTER PARSERS ---------
tree-sitter-c = "scm"
tree-sitter-lua = "scm"
tree-sitter-vim = "scm"
tree-sitter-vimdoc = "scm"
tree-sitter-query = "scm"
tree-sitter-latex = "scm"

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"

[plugins."lsp_lines.nvim"]
git = "https://git.sr.ht/~whynothugo/lsp_lines.nvim"

[plugins."gitsigns.nvim"]
git = "lewis6991/gitsigns.nvim"
rev = "v0.7"

[plugins."toggleterm.nvim"]
git = "akinsho/toggleterm.nvim"

[plugins.nvim-parinfer]
git = "gpanders/nvim-parinfer"

[plugins."lexima.vim"]
git = "cohama/lexima.vim"

[plugins.nvim-cmp]
git = "hrsh7th/nvim-cmp"

[plugins.cmp_luasnip]
git = "saadparwaiz1/cmp_luasnip"

[plugins.cmp-nvim-lsp]
git = "hrsh7th/cmp-nvim-lsp"

[plugins."github-preview.nvim"]
git = "wallpants/github-preview.nvim"
rev = "v1.9.0"

[config]
auto_setup = true
